login
Jonas-Grill/ready-to-ride pull request #18
Opened 2022-06-08 07:05 UTC by Al3x1999

2022-06-08 08:46 UTC, Jonas-Grill requested changes

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/MainActivity.kt
> +    }*/
Kann der Kommentar nicht weg?

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/contact/ContactFragment.kt
> +        //view.findViewById<Button>(R.id.sentButton).setOnClickListener{}
Unötige Kommentare bitte weg

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/contact/ContactFragment.kt
> +
Warum denn so viele Leerzeile reicht nicht eine?

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/AdminRegisterFragment.kt
> +    }
Da stimmt iwas nicht. Hast du zwei weiter Buttons?

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/AdminRegisterFragment.kt
> +// TODO: Rename parameter arguments, choose names that match
Dann mach es doch auch :D

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/AdminRegisterFragment.kt
> +        // TODO: Rename and change types and number of parameters
Dann mach es doch auch :D

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/LoginFragment.kt
> +// TODO: Rename parameter arguments, choose names that match
Wieder ein TODO

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/LoginFragment.kt
> +        // TODO: Rename and change types and number of parameters
Noch ein TODO :D

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +// TODO: Rename parameter arguments, choose names that match
Du magst TODOs oder?

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +    // TODO: Rename and change types of parameters
Das TODO macht aber auch sinn. param1 und param 2 sind nicht sehr eindeutig :D

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +            }
Wenn du es nicht brauchst kannst du das glaube ich weg machen

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +        }
Mach das bitte einen ClickListner, weil so navigiert das auch weiter wenn die eingaben falsch sind oder nicht?
Aber generell lieber ein ClickListner pro Button

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +        // TODO: Rename and change types and number of parameters
Du mit deinen TODOs 🤣

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +// TODO: Rename parameter arguments, choose names that match
TODO

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Warum so viele leerzeilen?

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +        }
Hier wieder das gleiche wie eben bitte nur ein clicklistner

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +        // TODO: Rename and change types and number of parameters
TODO

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/UserRegisterFragment.kt
> +// TODO: Rename parameter arguments, choose names that match
TODO

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/login/UserRegisterFragment.kt
> +        }
Wieder das mit den listnern

2022-06-08 08:46 UTC, Jonas-Grill commented on frontend/app/src/main/res/layout/fragment_register.xml
> +
Das sind viele leerzeilen

2022-06-08 08:53 UTC, Al3x1999 commented on frontend/app/src/main/java/com/readytoride/ui/contact/ContactFragment.kt
> +        //view.findViewById<Button>(R.id.sentButton).setOnClickListener{}
für logik vom abschicken, nur noch nicht angebunden

2022-06-08 08:54 UTC, Jonas-Grill commented on frontend/app/src/main/java/com/readytoride/ui/contact/ContactFragment.kt
> +        //view.findViewById<Button>(R.id.sentButton).setOnClickListener{}
Ahh ok

2022-06-09 09:50 UTC, Al3x1999 commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +            }
würde ich lassen zwecks falls man es noch braucht

2022-06-09 10:00 UTC, annekr requested changes
Nichts schlimmes, aber muss trotzdem gemacht werden :)

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/contact/ContactFragment.kt
> +        //view.findViewById<Button>(R.id.sentButton).setOnClickListener{}
Bitte auskommentieren. Macht ja aktuell nichts, dann ist auch kein Kommentar notwendig. Lieber dann in den onClickListener kommentieren, dass da noch eine Logik kommt

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/LoginFragment.kt
> +        // TODO: Rename and change types and number of parameters
Bitte doppelte Leerzeile in 18/19, 23/24, 34/35 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/LoginFragment.kt
> +        // TODO: Rename and change types and number of parameters
Bitte doppelte Leerzeile in 18/19, 23/24, 34/35 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/AdminRegisterFragment.kt
> +        // TODO: Rename and change types and number of parameters
Doppelte Leerzeilen entfernen in 37/38, 54/55

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/AdminRegisterFragment.kt
> +        // TODO: Rename and change types and number of parameters
Doppelte Leerzeilen entfernen in 37/38, 54/55

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +        }
Doppelte Leerzeilen entfernen in 75/76

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/RegisterFragment.kt
> +        }
Doppelte Leerzeilen entfernen in 75/76

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 63/37 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 63/37 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 39/40 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 39/40 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
*36/37

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
*36/37

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 46/47 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/java/com/readytoride/ui/login/TrainerRegisterFragment.kt
> +
Doppelte Leerzeilen in 46/47 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Und schon wieder doppelte Leerzeilen in 17/18 ;)

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Und schon wieder doppelte Leerzeilen in 17/18 ;)

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Doppelte Leerzeilen 65/66

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Doppelte Leerzeilen 65/66

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Doppelte Leerzeilen 79/80

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +
Doppelte Leerzeilen 79/80

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +<LinearLayout
Bitte obendrüber Leerzeile hinzufügen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +<LinearLayout
Bitte obendrüber Leerzeile hinzufügen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +
Doppelte Leerzeile 15/16

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +
Doppelte Leerzeile 15/16

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +        />
Schließende Klammer bitte in Zeile 22 noch packen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +        />
Schließende Klammer bitte in Zeile 22 noch packen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +
Doppelte Leerzeile 16/17

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +
Doppelte Leerzeile 16/17

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +
Doppelte Leerzeile 34/35

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +
Doppelte Leerzeile 34/35

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +        <ImageView
Doppelte Leerzeile 17/18

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +        <ImageView
Doppelte Leerzeile 17/18

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +
Doppelte Leerzeile

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +
Doppelte Leerzeile

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +                android:text="Registrieren" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_admin_register.xml
> +                android:text="Registrieren" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +    android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +    android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +            android:text="Login"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +            android:text="Login"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +            android:text="Registrieren"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_login.xml
> +            android:text="Registrieren"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml. Den kann man dann auch wiederverwenden

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml. Den kann man dann auch wiederverwenden

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Fokus auf:" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Fokus auf:" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Kinder" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Kinder" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Erwachsene" />
Bitte Text in die String Datei packen und nicht direkt in die xml. Kannst auch schauen, ob da die entsprechenden Texte schon vorhanden sind und die mit den IDs wiederverwenden

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Erwachsene" />
Bitte Text in die String Datei packen und nicht direkt in die xml. Kannst auch schauen, ob da die entsprechenden Texte schon vorhanden sind und die mit den IDs wiederverwenden

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Tunierreiter" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Tunierreiter" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Anfänger" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Anfänger" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Fortgeschrittene" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                    android:text="Fortgeschrittene" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                android:text="Registrieren" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_trainer_register.xml
> +                android:text="Registrieren" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +            android:text="Ready to Ride"
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +        <LinearLayout
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +        <LinearLayout
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Erfahrung" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Erfahrung" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Anfänger" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Anfänger" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Fortgeschrittener" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Fortgeschrittener" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Tunierreiter" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +                    android:text="Tunierreiter" />
Bitte Text in die String Datei packen und nicht direkt in die xml

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/layout/fragment_user_register.xml
> +
Doppelte Leerzeilen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="action_sign_in">Sign in or register</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="action_sign_in">Sign in or register</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="prompt_password">Password</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="prompt_password">Password</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="prompt_email">Email</string>
Das Ding wird E-Mail geschrieben

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="prompt_email">Email</string>
Das Ding wird E-Mail geschrieben

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="action_sign_in_short">Sign in</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="action_sign_in_short">Sign in</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="welcome">"Welcome!"</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="welcome">"Welcome!"</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="invalid_username">Not a valid username</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="invalid_username">Not a valid username</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="invalid_password">Password must be >5 characters</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="invalid_password">Password must be >5 characters</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="login_failed">"Login failed"</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="login_failed">"Login failed"</string>
Bitte deutsch

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Kannst du das bitte auch machen? :D Zeile darunter ist gemeint ;) und dann kannst du gleich auch noch die doppelten Leerzeichen in 147/148 entfernen

2022-06-09 10:00 UTC, annekr commented on frontend/app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Kannst du das bitte auch machen? :D Zeile darunter ist gemeint ;) und dann kannst du gleich auch noch die doppelten Leerzeichen in 147/148 entfernen

2022-06-09 19:26 UTC, Jonas-Grill approved these changes

2022-06-09 19:28 UTC, merged